ignore_sheet_mark = "~"
ignore_field_mark = "*"
custom_generator = "GDS2.0"
input = "data"
output = "dist"
project_root = "../"

[localization]
babel_keywords = [ "tr", "Label/text",]
pot_file = "lang/template.pot"
